# - Try to find Fuse
# Once done this will define
#
#  FUSE_FOUND - system has Fuse
#  FUSE_INCLUDE_DIR - the Fuse include directory
#  FUSE_LIBRARY - Link these to use Fuse
#

IF (FUSE_INCLUDE_DIR AND FUSE_LIBRARY)
   # in cache already
   SET(Fuse_FIND_QUIETLY TRUE)
ENDIF (FUSE_INCLUDE_DIR AND FUSE_LIBRARY)

FIND_PATH(FUSE_INCLUDE_DIR fuse.h
  /usr/include
  /usr/local/include
)

FIND_LIBRARY(FUSE_LIBRARY NAMES fuse
  PATHS
  /usr/${LIB_DESTINATION}
  /usr/local/${LIB_DESTINATION})

IF (FUSE_INCLUDE_DIR AND FUSE_LIBRARY)
   SET(Fuse_FOUND TRUE)
ELSE (FUSE_INCLUDE_DIR AND FUSE_LIBRARY)
   SET(Fuse_FOUND FALSE)
ENDIF (FUSE_INCLUDE_DIR AND FUSE_LIBRARY)

IF(Fuse_FOUND)
  IF(NOT Fuse_FIND_QUIETLY)
    MESSAGE(STATUS "Found Fuse: ${FUSE_LIBRARY}")
  ENDIF(NOT Fuse_FIND_QUIETLY)
ELSE(Fuse_FOUND)
  IF(Fuse_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Fuse")
  ENDIF(Fuse_FIND_REQUIRED)
ENDIF(Fuse_FOUND)

MARK_AS_ADVANCED(FUSE_INCLUDE_DIR FUSE_LIBRARY)
